name: PHP Composer

on:
  push:
    branches: [ "main" ]
    paths:
      - ./calendar-sync-module
      - .github/workflows/php.yaml
  pull_request:
    branches: [ "main" ]
    paths:
      - ./calendar-sync-module
      - .github/workflows/php.yaml

jobs:
  # Job 1: Test Code (Chạy môi trường PHP thuần cho nhanh)
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./php-service # Quan trọng: Trỏ đúng thư mục chứa code

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_mysql, zip
          coverage: none

      # Nếu bạn dùng Composer
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      # Nếu bạn có file test (PHPUnit)
      - name: Run Tests
        run: composer analyse
        # Nếu chưa có test thì tạm thời comment dòng trên và dùng lệnh echo để test flow
        # run: echo "Running tests..."

  # Job 2: Kích hoạt Render Build & Deploy
  deploy:
    needs: test # Chỉ chạy khi test pass
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        # Gọi Webhook để Render bắt đầu build Dockerfile từ repo
        run: curl -X POST ${{ secrets.RENDER_PHP_HOOK }}
